'use client';
import { useEffect, useState } from 'react';
import { api, accessToken } from '../../../lib/api';
import { TransactionWorkspace } from '../../../components/workspace/TransactionWorkspace';
export default function QuotePage({ params }: { params: { id: string } }) {
 const [quote,setQuote]=useState<any>(null); const [status,setStatus]=useState('');
 useEffect(()=>{const t=accessToken(); if(t) api<any>(`/quotes/${params.id}`,{},t).then(setQuote).catch(e=>setStatus(e.message));},[params.id]);
 async function accept(){const t=accessToken(); if(!t)return; try{setStatus('Accepting…'); const q=await api<any>(`/quotes/${params.id}/accept`,{method:'POST'},t); setQuote((x:any)=>({...x,...q})); setStatus('Quote accepted. You can now create the Order Intent.');}catch(e:any){setStatus(e.message)}}
 async function orderIntent(){const t=accessToken(); if(!t)return; try{setStatus('Creating Order Intent…'); await api(`/order-intents/${params.id}`,{method:'POST'},t); setStatus('Order Intent created successfully.');}catch(e:any){setStatus(e.message)}}
 if(!quote)return <main className="min-h-screen bg-black p-6 text-white">{status||'Loading…'}</main>;
 return <main className="min-h-screen bg-black p-5 text-white"><div className="mx-auto max-w-4xl"><div className="text-xs tracking-[.3em] text-white/40">SEPTLION / QUOTE</div><h1 className="mt-3 text-3xl font-semibold">Commercial Quote</h1><div className="mt-8 rounded-3xl border border-white/10 p-6"><div className="flex justify-between"><span className="text-white/50">Status</span><span>{quote.status}</span></div><div className="mt-6 space-y-3">{quote.items.map((i:any)=><div key={i.id} className="flex justify-between rounded-xl bg-white/[.03] p-4"><span>{i.sku?.name || i.skuId}</span><span>{i.quantity} × {i.unitPrice} {quote.currency}</span></div>)}</div><div className="mt-6 grid gap-3 text-sm text-white/60 md:grid-cols-2"><div>Payment: {quote.paymentTerms || '—'}</div><div>Shipping: {quote.shippingTerms || '—'}</div><div>Valid until: {quote.validUntil ? new Date(quote.validUntil).toLocaleDateString() : '—'}</div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row">{['SUBMITTED','REVISED'].includes(quote.status)&&<button onClick={accept} className="rounded-xl bg-white px-5 py-3 font-semibold text-black">Accept Quote</button>}{quote.status==='ACCEPTED'&&<button onClick={orderIntent} className="rounded-xl bg-white px-5 py-3 font-semibold text-black">Create Order Intent</button>}</div>{status&&<div className="mt-4 text-sm text-white/50">{status}</div>}</div><TransactionWorkspace entityType="QUOTE" entityId={params.id}/></div></main>;
}
