'use client';
import {FormEvent,useMemo,useState} from 'react';

const copy={
en:{nav:['How it works','Supply cases','Industries'],eyebrow:'DEMAND-LED PRODUCT DEVELOPMENT & MANAGED SUPPLY',titleA:'You define the need.',titleB:'Septlion builds the supply.',intro:'We turn a clear buyer requirement into a production-ready product, a qualified supply program, and managed cross-border execution across MENA and Africa.',primary:'Build my product',secondary:'See how it works',proof:['Buyer-led','Specification-first','Execution-managed'],architecture:'One operating path. From need to repeat supply.',architectureText:'Septlion coordinates the hard middle between demand and delivery—so buyers are not left managing disconnected factories, packaging vendors, freight agents, and documents.',steps:[['01','Define the need','Product, market, target cost, volume, compliance, and delivery requirements.'],['02','Engineer the supply','Technical configuration, supplier qualification, samples, costing, and risk checks.'],['03','Execute the program','Commercial offer, production control, documents, logistics, and delivery.'],['04','Repeat and scale','A documented supply case becomes a repeatable program across markets and SKUs.']],casesTitle:'Supply cases, not a supplier directory.',casesText:'Every request becomes a controlled execution record with a specification version, commercial options, approvals, and a clear next action.',case1:['Custom PR Packaging Program','10,000 finished kits','Saudi Arabia','Specification → supplier costing → three execution levels → sample approval'],case2:['Private-Label Food Program','Export-ready consumer formats','MENA & Africa','Buyer requirement → product configuration → compliance → export delivery'],industries:'Built for products that need coordination.',industryItems:['Food & private label','Packaging & print','Consumer goods','Industrial sourcing'],formTitle:'Build My Product',formText:'Tell us what the market needs. We will structure the product and the supply program.',labels:['What do you need to build?','Target market','Estimated quantity','Target delivery date','Work email or WhatsApp'],placeholders:['Example: 10,000 custom PR kits with six inner pouches','Country or region','Units, cartons, tons, or containers','Month / date','name@company.com or + country code'],submit:'Create my supply brief',sent:'Supply brief created',sentText:'Your requirement is structured. Septlion will use it as the starting point for qualification and technical alignment.',footer:'Septlion LLC · United States · Serving MENA & Africa',switcher:'العربية'},
ar:{nav:['كيف نعمل','حالات التوريد','القطاعات'],eyebrow:'تطوير المنتجات والتوريد المُدار انطلاقًا من احتياج السوق',titleA:'أنت تحدد الاحتياج.',titleB:'سبتليون تبني التوريد.',intro:'نحوّل احتياج المشتري الواضح إلى منتج جاهز للتصنيع، وبرنامج توريد مؤهل، وتنفيذ مُدار عبر الشرق الأوسط وأفريقيا.',primary:'ابنِ منتجي',secondary:'اعرف كيف نعمل',proof:['بقيادة الطلب','المواصفة أولًا','تنفيذ مُدار'],architecture:'مسار تشغيل واحد، من الاحتياج إلى التوريد المتكرر.',architectureText:'تدير سبتليون الحلقة الأصعب بين الطلب والتسليم، حتى لا يضطر المشتري إلى إدارة مصانع وموردي عبوات وشحن ومستندات منفصلة.',steps:[['٠١','تحديد الاحتياج','المنتج والسوق والتكلفة المستهدفة والكمية والامتثال والتسليم.'],['٠٢','هندسة التوريد','ضبط المواصفة وتأهيل الموردين والعينات والتكلفة وفحص المخاطر.'],['٠٣','تنفيذ البرنامج','العرض التجاري وضبط الإنتاج والمستندات والشحن والتسليم.'],['٠٤','التكرار والتوسع','تتحول حالة التوريد الموثقة إلى برنامج قابل للتكرار عبر الأسواق والمنتجات.']],casesTitle:'حالات توريد، لا دليل موردين.',casesText:'يتحول كل طلب إلى سجل تنفيذ مضبوط يضم نسخة المواصفة والخيارات التجارية والاعتمادات والخطوة التالية.',case1:['برنامج تغليف علاقات عامة مخصص','10,000 طقم مكتمل','السعودية','مواصفة ← تكلفة المورد ← ثلاثة مستويات تنفيذ ← اعتماد العينة'],case2:['برنامج غذائي بعلامة خاصة','عبوات استهلاكية جاهزة للتصدير','الشرق الأوسط وأفريقيا','احتياج المشتري ← تكوين المنتج ← الامتثال ← التسليم التصديري'],industries:'مصممة للمنتجات التي تحتاج إلى تنسيق.',industryItems:['الأغذية والعلامة الخاصة','التغليف والطباعة','السلع الاستهلاكية','التوريد الصناعي'],formTitle:'ابنِ منتجي',formText:'أخبرنا بما يحتاجه السوق، وسنحوّله إلى منتج وبرنامج توريد منظم.',labels:['ما المنتج الذي تريد بناءه؟','السوق المستهدف','الكمية التقديرية','موعد التسليم المستهدف','البريد المهني أو واتساب'],placeholders:['مثال: 10,000 طقم علاقات عامة مخصص','الدولة أو المنطقة','وحدة، كرتونة، طن أو حاوية','الشهر أو التاريخ','name@company.com أو رقم واتساب'],submit:'أنشئ موجز التوريد',sent:'تم إنشاء موجز التوريد',sentText:'تم تنظيم احتياجك، وسيكون نقطة البداية للتأهيل والمواءمة الفنية مع سبتليون.',footer:'Septlion LLC · شركة أمريكية · نخدم الشرق الأوسط وأفريقيا',switcher:'English'}};

export default function Home(){const[lang,setLang]=useState<'en'|'ar'>('en');const[sent,setSent]=useState(false);const t=useMemo(()=>copy[lang],[lang]);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)}return <main dir={lang==='ar'?'rtl':'ltr'} className={lang==='ar'?'arabic':''}>
<header className="nav shell"><a className="brand" href="#top"><span className="mark">S</span><span>SEPTLION <b>SUPPLY</b></span></a><nav>{t.nav.map((item,i)=><a key={item} href={['#process','#cases','#industries'][i]}>{item}</a>)}</nav><div className="nav-actions"><button className="language" onClick={()=>setLang(lang==='en'?'ar':'en')}>{t.switcher}</button><a className="nav-cta" href="#build">{t.primary}</a></div></header>
<section id="top" className="hero shell"><div className="orb orb-one"/><div className="orb orb-two"/><p className="eyebrow"><span/>{t.eyebrow}</p><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p className="lead">{t.intro}</p><div className="hero-actions"><a className="button gold" href="#build">{t.primary}<span>↗</span></a><a className="button ghost" href="#process">{t.secondary}<span>↓</span></a></div><div className="proof">{t.proof.map((item,i)=><div key={item}><span>0{i+1}</span>{item}</div>)}</div></section>
<section id="process" className="section shell"><div className="section-head"><div><p className="kicker">SUPPLY ARCHITECTURE</p><h2>{t.architecture}</h2></div><p>{t.architectureText}</p></div><div className="steps">{t.steps.map(s=><article key={s[0]}><span className="step-number">{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section>
<section id="cases" className="section section-dark"><div className="shell"><div className="section-head split"><div><p className="kicker">SUPPLY CASES</p><h2>{t.casesTitle}</h2></div><p>{t.casesText}</p></div><div className="cases"><Case data={t.case1} index="01"/><Case data={t.case2} index="02"/></div></div></section>
<section id="industries" className="section shell industries"><p className="kicker">INDUSTRIES</p><h2>{t.industries}</h2><div className="industry-grid">{t.industryItems.map((item,i)=><div key={item}><span>{String(i+1).padStart(2,'0')}</span><h3>{item}</h3><b>↗</b></div>)}</div></section>
<section id="build" className="section build-wrap"><div className="shell build-grid"><div className="build-copy"><p className="kicker">START WITH DEMAND</p><h2>{t.formTitle}</h2><p>{t.formText}</p><div className="mini-path"><span>NEED</span><i>→</i><span>SPEC</span><i>→</i><span>SUPPLY</span><i>→</i><span>DELIVERY</span></div></div><div className="form-card">{sent?<div className="success"><div>✓</div><h3>{t.sent}</h3><p>{t.sentText}</p><button onClick={()=>setSent(false)}>{lang==='ar'?'إنشاء طلب آخر':'Create another brief'}</button></div>:<form onSubmit={submit}>{t.labels.map((label,i)=><label key={label} className={i===0||i===4?'wide':''}><span>{label}</span>{i===0?<textarea required placeholder={t.placeholders[i]}/>:<input required={i===4} placeholder={t.placeholders[i]}/>}</label>)}<button className="submit" type="submit">{t.submit}<span>↗</span></button></form>}</div></div></section>
<footer className="footer shell"><div className="brand"><span className="mark">S</span><span>SEPTLION <b>SUPPLY</b></span></div><p>{t.footer}</p><a href="#top">↑</a></footer></main>}
function Case({data,index}:{data:string[],index:string}){return <article className="case"><div className="case-visual"><span>{index}</span><div className="heptagon"/></div><div className="case-body"><p>{data[2]}</p><h3>{data[0]}</h3><strong>{data[1]}</strong><div className="case-flow">{data[3]}</div></div></article>}
