import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as nodeModule from 'node:module';
import {test} from 'node:test';
let transpile;
try{const{default:ts}=await import('typescript');transpile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;}
catch{transpile=s=>nodeModule.stripTypeScriptTypes(s,{mode:'strip'});}
const source=async name=>readFile(new URL('../supabase/functions/trade-api/'+name,import.meta.url),'utf8');
const url=s=>'data:text/javascript;base64,'+Buffer.from(transpile(s)).toString('base64');
const lifecycleUrl=url(await source('lifecycle-input.ts')),documentUrl=url(await source('document-input.ts'));
const lifecycle=await import(lifecycleUrl),documents=await import(documentUrl);
const apiUrl=url((await source('lifecycle-api.ts')).replace("'./lifecycle-input.ts'",JSON.stringify(lifecycleUrl)).replace("'./document-input.ts'",JSON.stringify(documentUrl)));
const offerUrl=url(await source('offer-input.ts'));
const prepared=(await source('index.ts')).replace('import "jsr:@supabase/functions-js/edge-runtime.d.ts";','').replace('import { createClient } from "npm:@supabase/supabase-js@2";','const createClient=()=>globalThis.__tradeDb;').replace('"./offer-input.ts"',JSON.stringify(offerUrl)).replace('"./lifecycle-api.ts"',JSON.stringify(apiUrl)).replace('Deno.serve(async(req)=>{','export const handler=async(req)=>{').replace(/\}\);\s*$/,'};');
globalThis.Deno={env:{get:()=> 'fixture-server-config'}};
// Secret map must be JSON; no network or live tokens are used in these tests.
globalThis.Deno.env.get=name=>name==='SUPABASE_SECRET_KEYS'?'{}':'fixture-server-config';
const{handler}=await import(url(prepared));
class Query {
 constructor(rows){this.rows=rows;this.filters=[];this.max=Infinity;}
 select(){return this;}eq(k,v){this.filters.push(r=>r[k]===v);return this;}in(k,v){this.filters.push(r=>v.includes(r[k]));return this;}order(){return this;}limit(n){this.max=n;return this;}
 result(){return this.rows.filter(row=>this.filters.every(f=>f(row))).slice(0,this.max);}
 then(resolve,reject){return Promise.resolve({data:this.result(),error:null}).then(resolve,reject);}
 async maybeSingle(){return{data:this.result()[0]||null,error:null};}async single(){return{data:this.result()[0]||null,error:null};}
}
const bytes=Buffer.from('%PDF-1.4\nTEST NONCOMMERCIAL\n%%EOF');
const hash=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex');
function fixture({operator=true,buyer='buyer-1',active=true,valid=true}={}) {
 const user={id:'user-1',email:'info@septlion.com',isActive:active};
 const tables={User:[user],Membership:[{id:'mb',userId:user.id,organizationId:buyer,role:'BUYER'},...(operator?[{id:'mo',userId:user.id,organizationId:'septlion-operator',role:'SALES'}]:[])],Organization:[{id:buyer,status:'ACTIVE'},{id:'septlion-operator',status:'ACTIVE'}],TradeTransaction:[{id:'tx-1',reference:'TEST-TX-001',buyerOrgId:'buyer-1',supplierOrgId:'septlion-operator',status:'COMMITTED',testOnly:true,version:1,commercialLockId:'lock-1'}],CommercialLock:[{id:'lock-1',offerId:'offer-1',snapshot:{items:[{quantity:1,unit:'FCL'}],testOnly:true,supplyEvidence:{reference:'PRIVATE-PROCUREMENT'}}}],SeptlionOffer:[{id:'offer-1',requirementId:'req-1'}],QualifiedRequirement:[{id:'req-1',unit:'FCL'}],TradeMilestone:[],TradeEvent:[],TradeClaim:[],TradeReceipt:[],CommercialDocument:[{id:'doc-1',organizationId:'septlion-operator',uploadedById:'user-1',entityType:'TRANSACTION',entityId:'tx-1',storageKey:'transactions/tx-1/doc-1.pdf',fileName:'test.pdf',mimeType:'application/pdf',byteSize:bytes.length,sha256:hash,kind:'PACKING_LIST',status:'PENDING',visibilityToCounterparty:true}]};
 const calls=[],storageCalls=[];let content=bytes;
 const db={schema:()=>db,auth:{getUser:async()=>({data:{user:valid?user:null},error:valid?null:{message:'invalid'}})},from:name=>new Query(tables[name]||[]),
  rpc:async(name,args)=>{calls.push({name,args});if(name==='check_edge_rate_limit')return{data:true,error:null};if(name==='prepare_trade_document')return{data:{id:'doc-1',status:'PENDING',storageKey:tables.CommercialDocument[0].storageKey},error:null};if(name==='finalize_trade_document'){tables.CommercialDocument[0].status=args.p_valid?'READY':'QUARANTINED';return{data:{id:'doc-1',status:tables.CommercialDocument[0].status},error:null};}return{data:{transactionId:'tx-1',idempotent:false},error:null};},
  storage:{getBucket:async()=>({data:null,error:{message:'Bucket not found'}}),createBucket:async(name,options)=>{storageCalls.push({operation:'createBucket',name,options});return{error:null};},from:bucket=>({createSignedUploadUrl:async(path,options)=>{storageCalls.push({operation:'upload',bucket,path,options});return{data:{signedUrl:'https://fixture.invalid/private-upload'},error:null};},download:async path=>{storageCalls.push({operation:'read',path});return{data:new Blob([content]),error:null};},createSignedUrl:async(path,expiry,options)=>{storageCalls.push({operation:'download',path,expiry,options});return{data:{signedUrl:'https://fixture.invalid/private-download'},error:null};}})}
 };
 return{db,tables,calls,storageCalls,setContent:value=>{content=value;}};
}
async function call(f,action,payload={},origin='https://septlion.com'){globalThis.__tradeDb=f.db;const r=await handler(new Request('https://fixture.invalid/trade-api',{method:'POST',headers:{Authorization:'Bearer TEST-FIXTURE',Origin:origin},body:JSON.stringify({...payload,action})}));return{status:r.status,body:await r.json(),origin:r.headers.get('access-control-allow-origin')};}
test('API denies invalid sessions, inactive users and forged operator flags without writes',async()=>{
 for(const options of [{valid:false},{active:false},{operator:false}]){const f=fixture(options);const r=await call(f,'transactions.advance',{transactionId:'tx-1',isOperator:true});assert.equal(r.status,options.valid===false?401:403);assert.equal(f.calls.filter(x=>x.name!=='check_edge_rate_limit').length,0);}
});
test('email equality does not bootstrap operator rights',async()=>{const f=fixture({operator:false});assert.equal((await call(f,'operator.transaction',{id:'tx-1'})).status,403);});
test('foreign buyer cannot read a transaction or its documents even when sharing was enabled',async()=>{const f=fixture({operator:false,buyer:'stranger'});for(const[action,payload]of[['transactions.get',{id:'tx-1'}],['documents.list',{transactionId:'tx-1'}],['documents.download',{documentId:'doc-1'}]])assert.equal((await call(f,action,payload)).status,404);assert.equal(f.storageCalls.length,0);});
test('buyer sees shared counterparty documents but not private or unrelated organization files',async()=>{
 const f=fixture({operator:false}),base={...f.tables.CommercialDocument[0],status:'READY'};f.tables.CommercialDocument=[base,{...base,id:'private',visibilityToCounterparty:false},{...base,id:'foreign',organizationId:'stranger'}];const r=await call(f,'documents.list',{transactionId:'tx-1'});assert.equal(r.status,200);assert.deepEqual(r.body.items.map(x=>x.id),['doc-1']);assert.equal(r.body.items[0].storageKey,undefined);assert.equal(r.body.items[0].sha256,undefined);
});
test('saved workspace omits procurement evidence in the commercial lock',async()=>{const f=fixture({operator:false});const r=await call(f,'transactions.get',{id:'tx-1'});assert.equal(r.status,200);assert.equal(r.body.item.testOnly,true);assert.equal(r.body.nextAction.status,'IN_EXECUTION');assert.doesNotMatch(JSON.stringify(r.body),/PRIVATE-PROCUREMENT/);});
test('acceptance requires explicit mode and revision and only calls the guarded RPC',async()=>{const f=fixture();assert.equal((await call(f,'offers.accept',{offerId:'offer-1'})).status,400);assert.equal((await call(f,'offers.accept',{offerId:'offer-1',revision:0,mode:'TEST'})).status,400);assert.equal((await call(f,'offers.accept',{offerId:'offer-1',revision:1,mode:'TEST'})).status,200);assert.deepEqual(f.calls.find(x=>x.name==='accept_trade_offer_v2').args,{p_offer_id:'offer-1',p_buyer_org_id:'buyer-1',p_user_id:'user-1',p_revision:1,p_mode:'TEST'});});
test('state updates reject mismatched milestones and carry version, note and idempotency key',async()=>{const f=fixture(),payload={transactionId:'tx-1',status:'IN_EXECUTION',milestoneCode:'PREPARATION',expectedVersion:1,note:'TEST — simulated preparation',idempotencyKey:'fixture-stage-001'};assert.equal((await call(f,'transactions.advance',{...payload,milestoneCode:'DELIVERED'})).status,400);assert.equal((await call(f,'transactions.advance',payload)).status,200);const args=f.calls.find(x=>x.name==='advance_trade_transaction_v2').args;assert.equal(args.p_key,payload.idempotencyKey);assert.equal(args.p_expected_version,1);assert.equal(args.p_note,payload.note);});
test('reorder rejects fractional container count instead of truncating it',async()=>{const f=fixture();assert.equal((await call(f,'reorder.create',{transactionId:'tx-1',quantity:7.5,idempotencyKey:'fixture-reorder-001'})).status,400);assert.equal(f.calls.some(x=>x.name==='reorder_trade_transaction_v2'),false);assert.equal((await call(f,'reorder.create',{transactionId:'tx-1',quantity:8,idempotencyKey:'fixture-reorder-001'})).status,201);assert.equal(f.calls.find(x=>x.name==='reorder_trade_transaction_v2').args.p_quantity,8);});
const metadata=()=>({transactionId:'tx-1',side:'OPERATOR',fileName:'test.pdf',mimeType:'application/pdf',byteSize:bytes.length,sha256:hash,kind:'PACKING_LIST',visibilityToCounterparty:true,idempotencyKey:'fixture-document-001'});
test('upload registration creates a private bounded bucket and server-minted path',async()=>{const f=fixture();const r=await call(f,'documents.prepare',metadata());assert.equal(r.status,201);assert.equal(r.body.documentId,'doc-1');const bucket=f.storageCalls.find(x=>x.operation==='createBucket');assert.equal(bucket.options.public,false);assert.equal(bucket.options.fileSizeLimit,10*1024*1024);assert.deepEqual(bucket.options.allowedMimeTypes,['application/pdf','image/png','image/jpeg']);const upload=f.storageCalls.find(x=>x.operation==='upload');assert.equal(upload.options.upsert,false);assert.equal(upload.path,'transactions/tx-1/doc-1.pdf');});
test('file metadata rejects traversal, mismatched extension, oversized files and ambiguous visibility',async()=>{for(const change of [x=>x.fileName='../test.pdf',x=>x.fileName='test.html',x=>x.byteSize=10*1024*1024+1,x=>delete x.visibilityToCounterparty,x=>x.sha256='invalid']){const x=metadata();change(x);assert.throws(()=>documents.documentInput(x));}});
test('completion verifies actual bytes and hash before the document becomes available',async()=>{const f=fixture();const r=await call(f,'documents.complete',{documentId:'doc-1',side:'OPERATOR'});assert.equal(r.status,200);assert.equal(f.calls.find(x=>x.name==='finalize_trade_document').args.p_valid,true);assert.equal(f.tables.CommercialDocument[0].status,'READY');});
test('tampered upload is quarantined and cannot produce a download link',async()=>{const f=fixture();f.setContent(Buffer.from('<html>tampered content</html>'));assert.equal((await call(f,'documents.complete',{documentId:'doc-1',side:'OPERATOR'})).status,400);assert.equal(f.tables.CommercialDocument[0].status,'QUARANTINED');assert.equal((await call(f,'documents.download',{documentId:'doc-1',side:'OPERATOR'})).status,404);assert.equal(f.storageCalls.some(x=>x.operation==='download'),false);});
test('only the uploader can complete a pending document',async()=>{const f=fixture();f.tables.CommercialDocument[0].uploadedById='different-user';assert.equal((await call(f,'documents.complete',{documentId:'doc-1',side:'OPERATOR'})).status,404);assert.equal(f.storageCalls.length,0);});
test('private downloads expire in 60 seconds and use the saved filename',async()=>{const f=fixture({operator:false});f.tables.CommercialDocument[0].status='READY';const r=await call(f,'documents.download',{documentId:'doc-1'});assert.equal(r.status,200);const download=f.storageCalls.find(x=>x.operation==='download');assert.equal(download.expiry,60);assert.equal(download.options.download,'test.pdf');assert.equal(r.body.expiresIn,60);});
test('PDF integrity validation rejects matching size with changed content and accepts unchanged bytes',async()=>{await documents.checkDocumentBytes(bytes,'application/pdf',bytes.length,hash);const changed=Buffer.from(bytes);changed[10]=42;await assert.rejects(()=>documents.checkDocumentBytes(changed,'application/pdf',bytes.length,hash));});
test('methods, malformed JSON and oversized metadata requests fail clearly',async()=>{const f=fixture();globalThis.__tradeDb=f.db;for(const[method,body,status]of[['GET',null,405],['POST','{',400],['POST','[]',400],['POST','x'.repeat(65537),413]]){const r=await handler(new Request('https://fixture.invalid/trade-api',{method,...(body?{body}:{})}));assert.equal(r.status,status);}assert.equal(f.calls.length,0);});
test('parallel requests preserve their own allowed CORS origin',async()=>{const f=fixture();const result=await Promise.all([call(f,'me',{},'https://septlion.com'),call(f,'me',{},'https://www.septlion.com')]);assert.deepEqual(result.map(x=>x.origin),['https://septlion.com','https://www.septlion.com']);});
