import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';import {Prisma,RequirementStatus} from '@prisma/client';import {PrismaService} from '../prisma/prisma.service';import {TenantContextService} from '../common/tenant/tenant-context.service';import {CreateRequirementDto,PatchRequirementDto} from './requirement.dto';
const json=(v:unknown)=>v as Prisma.InputJsonValue;
@Injectable() export class RequirementService{
 constructor(private prisma:PrismaService,private tenant:TenantContextService){}
 list(){const org=this.tenant.organizationId;return this.prisma.tenantTransaction(org,tx=>tx.qualifiedRequirement.findMany({where:{organizationId:org},orderBy:{updatedAt:'desc'},take:100}))}
 get(id:string){const org=this.tenant.organizationId;return this.prisma.tenantTransaction(org,async tx=>{const r=await tx.qualifiedRequirement.findFirst({where:{id,organizationId:org}});if(!r)throw new NotFoundException('الطلب غير موجود');return r})}
 create(dto:CreateRequirementDto){const org=this.tenant.organizationId;return this.prisma.tenantTransaction(org,tx=>tx.qualifiedRequirement.create({data:{organizationId:org,source:'AI_COMPOSER',status:'DRAFT',product:dto.product,market:dto.market,quantity:dto.quantity,unit:dto.unit,deliveryCountry:dto.deliveryCountry,deliveryPort:dto.deliveryPort,incoterm:dto.incoterm,paymentPreference:dto.paymentPreference,requiredDate:dto.requiredDate?new Date(dto.requiredDate):undefined,knownFacts:json(dto.knownFacts??{}),fieldStates:json(dto.fieldStates??{}),criticalMissing:json(dto.criticalMissing??[]),productConfiguration:dto.productConfiguration?json(dto.productConfiguration):undefined,specifications:dto.specifications?json(dto.specifications):undefined,packing:dto.packing?json(dto.packing):undefined}}))}
 patch(id:string,dto:PatchRequirementDto){const org=this.tenant.organizationId;return this.prisma.tenantTransaction(org,async tx=>{const r=await tx.qualifiedRequirement.findFirst({where:{id,organizationId:org}});if(!r)throw new NotFoundException('الطلب غير موجود');return tx.qualifiedRequirement.update({where:{id},data:{status:dto.status as RequirementStatus|undefined,knownFacts:dto.knownFacts?json(dto.knownFacts):undefined,inferredFacts:dto.inferredFacts?json(dto.inferredFacts):undefined,fieldStates:dto.fieldStates?json(dto.fieldStates):undefined,criticalMissing:dto.criticalMissing?json(dto.criticalMissing):undefined,productConfiguration:dto.productConfiguration?json(dto.productConfiguration):undefined,specifications:dto.specifications?json(dto.specifications):undefined,packing:dto.packing?json(dto.packing):undefined,confidence:dto.confidence}})})}
 async convertToRfq(id:string){const org=this.tenant.organizationId;return this.prisma.tenantTransaction(org,async tx=>{const req=await tx.qualifiedRequirement.findFirst({where:{id,organizationId:org}});if(!req)throw new NotFoundException('الطلب غير موجود');if(req.status!=='QUALIFIED'&&req.status!=='SUPPLY_READY')throw new BadRequestException('يجب تأهيل الطلب قبل إنشاء RFQ');const existing=await tx.rFQ.findUnique({where:{requirementId:id}});if(existing)return existing;const sector=await tx.sector.findFirst({where:{organizationId:org,status:'ACTIVE'},orderBy:{createdAt:'asc'}});if(!sector)throw new BadRequestException('لا يوجد قطاع نشط لإنشاء RFQ');const reference='RFQ-'+new Date().getUTCFullYear()+'-'+id.slice(0,8).toUpperCase();return tx.rFQ.create({data:{requirementId:id,buyerOrgId:org,sectorId:sector.id,reference,status:'SUBMITTED',deliveryCountry:req.deliveryCountry,deliveryPort:req.deliveryPort,incoterm:req.incoterm,requestedDate:req.requiredDate,notes:'Generated from qualified BuyerRequirement '+id}})})}
}