'use client';
import {FormEvent,useRef,useState} from 'react';
import {BuyerShell,Stage} from '../../components/buyer-shell';
import {useTradeWorkspace,TestNotice,WorkspaceFallback} from '../../components/trade-workspace';
import {edge} from '../../lib/api';
import {rememberActiveRequest} from '../../lib/buyer-ui-store';
import {errorMessage} from '../../lib/trade-transaction';
export default function Reorder(){const{data:w,loading,error:loadError,reload}=useTradeWorkspace();const[quantity,setQuantity]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<{id:string;reference:string}|null>(null);const pending=useRef<{signature:string;key:string}|null>(null);const prior=w?.commercialLock?.snapshot.items[0],containerUnit=['FCL','CONTAINER','CONTAINERS','TEU','FEU'].includes(prior?.unit?.toUpperCase()||'');
 async function reorder(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!w||w.item.status!=='COMPLETED'||busy||created)return;setBusy(true);setError('');try{const qty=quantity.trim()?Number(quantity):null;if(qty!==null&&(!Number.isFinite(qty)||qty<=0||(containerUnit&&!Number.isInteger(qty))))throw new Error(containerUnit?'أدخل عددًا صحيحًا موجبًا للحاويات.':'أدخل كمية موجبة.');const signature=JSON.stringify([w.item.id,qty]);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};const r=await edge<{id:string;reference:string}>('reorder.create',{transactionId:w.item.id,quantity:qty,idempotencyKey:pending.current.key});if(!r.id)throw new Error('تعذر قراءة الطلب الجديد.');rememberActiveRequest(r.id);setCreated(r);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <BuyerShell title="إعادة الطلب" eyebrow="REORDER"><section className="buyer-section"><Stage current={5}/><div className="section-intro"><small>TRADE MEMORY</small><h1>ابدأ الطلب التالي من التكوين المعتمد</h1><p>ينشأ طلب مفتوح جديد لإعادة التحقق من السعر والتوفر والشحن قبل إصدار عرض جديد.</p></div>{!w?<WorkspaceFallback loading={loading} error={loadError} onReload={()=>void reload()}/>:<><TestNotice testOnly={w.item.testOnly}/>{w.item.status!=='COMPLETED'?<div className="empty-state"><b>إعادة الطلب متاحة بعد اكتمال الصفقة</b></div>:created?<div className="action-card"><p className="workspace-success" role="status">تم إنشاء {w.item.testOnly?'طلب الاختبار':'طلب إعادة'} جديد. لم يُنسخ سعر العرض السابق.</p><b dir="ltr">{created.reference}</b><a className="primary-link wide" href={'/request?id='+encodeURIComponent(created.id)}>مراجعة الطلب الجديد</a></div>:<form className="action-card reorder-form" onSubmit={reorder}><small dir="ltr">{w.item.reference}</small><p>الكمية السابقة: {prior?.quantity??'—'} {prior?.unit||''}</p><label>الكمية الجديدة {prior?.unit?'('+prior.unit+')':''}<input type="number" min={containerUnit?'1':'0.0001'} max="1000000000" step={containerUnit?'1':'0.0001'} disabled={busy} value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="اتركها فارغة للاحتفاظ بالكمية السابقة"/></label><button className="primary-link" disabled={busy}>{busy?'جارٍ الإنشاء…':w.item.testOnly?'إنشاء إعادة طلب تجريبية':'إنشاء إعادة الطلب'}</button>{error&&<p className="workspace-error" role="alert">{error}</p>}</form>}</>}</section></BuyerShell>;}
