'use client';
import {useRef,useState} from 'react';
import {BuyerShell,Stage} from '../../components/buyer-shell';
import {useTradeWorkspace,TestNotice,WorkspaceFallback} from '../../components/trade-workspace';
import {edge} from '../../lib/api';
import {errorMessage} from '../../lib/trade-transaction';
export default function Receive(){const{data:w,requestId,loading,error:loadError,reload}=useTradeWorkspace();const[confirming,setConfirming]=useState(false),[issue,setIssue]=useState(false),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const key=useRef<{signature:string;key:string}|null>(null);const status=w?.item.status||'',open=w?.claims.some(x=>['OPEN','UNDER_REVIEW'].includes(x.status));const allowed=['DELIVERED','RECEIPT_REVIEW'].includes(status)&&!open;
 async function accept(){if(!w||!allowed||busy)return;setBusy(true);setError('');try{await edge('receipt.accept',{transactionId:w.item.id,expectedVersion:w.item.version});setMessage(w.item.testOnly?'اكتملت محاكاة الاستلام وحُفظت ذاكرة الحالة.':'تم تأكيد الاستلام وإغلاق الصفقة.');await reload();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function claim(){if(!w||!allowed||busy||description.trim().length<5)return;setBusy(true);setError('');try{const signature=JSON.stringify([w.item.id,description.trim()]);if(key.current?.signature!==signature)key.current={signature,key:crypto.randomUUID()};await edge('claims.open',{transactionId:w.item.id,expectedVersion:w.item.version,description:description.trim(),idempotencyKey:key.current.key});key.current=null;setMessage('تم حفظ المطالبة. سيظل تأكيد الاستلام متوقفًا حتى معالجتها.');setIssue(false);setDescription('');await reload();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <BuyerShell context={{requestId,transactionId:w?.item.id,offerId:w?.commercialLock?.offerId}} title="الاستلام" eyebrow="RECEIVE"><section className="buyer-section">{!w?<WorkspaceFallback loading={loading} error={loadError} onReload={()=>void reload()}/>:<><Stage current={status==='COMPLETED'?5:4}/><TestNotice testOnly={w.item.testOnly}/><div className="workspace-heading"><div className="section-intro"><small dir="ltr">{w.item.reference}</small><h1>{w.item.testOnly?'مراجعة الاستلام التجريبي':'الاستلام وإغلاق الصفقة'}</h1><p>راجع التسليم والمستندات، ثم أكّد المطابقة أو افتح مطالبة.</p></div><button className="secondary-link" disabled={busy||loading} onClick={()=>void reload()}>تحديث الحالة</button></div>
  {allowed?<div className="action-card"><h2>{w.item.testOnly?'هل اكتمل سيناريو الاستلام التجريبي؟':'هل استلمت الطلب كما تم الاتفاق؟'}</h2><div className="two-actions"><button className="primary-link" disabled={busy||loading} onClick={()=>setConfirming(true)}>{busy?'جارٍ الحفظ…':w.item.testOnly?'تأكيد الاستلام التجريبي':'نعم، الاستلام مطابق'}</button><button className="secondary-link" disabled={busy||loading} onClick={()=>{setConfirming(false);setIssue(x=>!x)}}>لدي مشكلة</button></div>{confirming&&<div className="receipt-confirmation" role="group" aria-label="مراجعة تأكيد الاستلام"><p>سيُسجل تأكيدك للاستلام المطابق وتُغلق هذه {w.item.testOnly?'الحالة التجريبية':'الصفقة'}: <b dir="ltr">{w.item.reference}</b>.</p><p>إذا وجدت نقصًا أو مشكلة، افتح مطالبة قبل التأكيد.</p><div className="two-actions"><button className="primary-link" disabled={busy||loading} onClick={()=>void accept()}>{busy?'جارٍ الحفظ…':'تأكيد المطابقة وإغلاق '+(w.item.testOnly?'المحاكاة':'الصفقة')}</button><button className="secondary-link" disabled={busy} onClick={()=>setConfirming(false)}>العودة للمراجعة</button></div></div>}{issue&&<div className="receipt-issue"><label>وصف المشكلة<textarea value={description} disabled={busy} onChange={e=>setDescription(e.target.value)} minLength={5} maxLength={2000} placeholder="صف المشكلة أو النقص الذي وجدته"/></label><button className="primary-link" disabled={busy||description.trim().length<5} onClick={()=>void claim()}>فتح مطالبة</button></div>}</div>:status==='COMPLETED'?<p className="workspace-success">{w.item.testOnly?'اكتملت حالة الاختبار غير التجارية.':'تم تأكيد الاستلام وإغلاق الصفقة.'}</p>:open?<p className="workspace-error">توجد مطالبة مفتوحة. تأكيد الاستلام متوقف حتى معالجتها.</p>:<div className="empty-state"><b>لم تصل الصفقة إلى مرحلة مراجعة الاستلام</b><p>يتاح التأكيد بعد تسجيل التسليم في مسار التنفيذ.</p></div>}
  {w.claims.length>0&&<div className="claim-workspace"><h2>المطالبات والمعالجة</h2>{w.claims.map(c=><article key={c.id}><b>{['OPEN','UNDER_REVIEW'].includes(c.status)?'قيد المعالجة':'تمت المعالجة'}</b><small>فُتحت: {new Date(c.createdAt).toLocaleString('ar')}{c.resolvedAt?' · أُغلقت: '+new Date(c.resolvedAt).toLocaleString('ar'):''}</small><p>{c.description}</p>{c.resolution?.note&&<p className="claim-resolution">المعالجة: {c.resolution.note}</p>}</article>)}</div>}
  {error&&<p role="alert" className="workspace-error">{error}</p>}{message&&<p role="status" className="workspace-success">{message}</p>}<div className="two-actions"><a className="secondary-link" href={'/documents?id='+encodeURIComponent(w.item.id)}>مراجعة المستندات</a>{status==='COMPLETED'&&<a className="primary-link" href={'/reorder?id='+encodeURIComponent(w.item.id)}>إعادة الطلب</a>}</div>
 </>}</section></BuyerShell>;}
