ALTER TYPE "WorkspaceEntityType" ADD VALUE IF NOT EXISTS 'TRANSACTION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRANSACTION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CLAIM';
