import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditAction, Prisma, RFQStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { TenantContextService } from '../common/tenant/tenant-context.service';
import { AuditService } from '../audit/audit.service';
import { CreateRfqDto } from './dto/create-rfq.dto';
import { assertRfqTransition } from './rfq-state';
@Injectable()
export class RfqService {
 constructor(private prisma:PrismaService,private tenant:TenantContextService,private audit:AuditService){}
 async create(dto:CreateRfqDto){const org=this.tenant.organizationId;if(!dto.items?.length)throw new BadRequestException('يجب أن يحتوي RFQ على عنصر واحد على الأقل');return this.prisma.tenantTransaction(org,async tx=>{const sector=await tx.sector.findUnique({where:{id:dto.sectorId},include:{policies:true}});if(!sector)throw new BadRequestException('القطاع غير موجود');const policy=sector.policies[0];const shippingRules=(policy?.shippingRules ?? {}) as any;const allowedIncoterms=Array.isArray(shippingRules.allowedIncoterms)?shippingRules.allowedIncoterms:[];if(dto.incoterm && allowedIncoterms.length && !allowedIncoterms.includes(dto.incoterm))throw new BadRequestException('Incoterm غير مسموح به لهذا القطاع');let supplier=dto.supplierOrgId;const items:any[]=[];for(const i of dto.items){const rows=await tx.$queryRaw<any[]>`SELECT * FROM septlion_public_skus(${dto.sectorId}::uuid, 200)`;const sku=rows.find((row:any)=>row.sku_id===i.skuId);if(!sku)throw new BadRequestException('SKU غير متاح أو غير منشور');const minimum=Math.max(Number(sku.minimum_order_qty),Number(policy?.minimumOrderQty ?? 0));if(minimum>i.quantity)throw new BadRequestException(`الكمية أقل من MOQ للمنتج ${sku.sku_name}`);if(i.unit!==sku.unit)throw new BadRequestException(`وحدة القياس غير صحيحة للمنتج ${sku.sku_name}`);if(!supplier)supplier=sku.organization_id;if(supplier!==sku.organization_id)throw new BadRequestException('كل عناصر RFQ يجب أن تكون من نفس المورد');items.push(i);}const rfq=await tx.rFQ.create({data:{buyerOrgId:org,supplierOrgId:supplier,sectorId:dto.sectorId,reference:`RFQ-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,status:RFQStatus.OPEN,deliveryCountry:dto.deliveryCountry,deliveryPort:dto.deliveryPort,incoterm:dto.incoterm,requestedDocuments:policy?.requiredDocuments ?? undefined,requestedDate:dto.requestedDate?new Date(dto.requestedDate):undefined,notes:dto.notes,items:{create:items.map(i=>({skuId:i.skuId,quantity:new Prisma.Decimal(i.quantity),unit:i.unit,targetPrice:i.targetPrice==null?undefined:new Prisma.Decimal(i.targetPrice)}))}},include:{items:true}});await this.audit.record(tx,{organizationId:org,userId:this.tenant.userId,action:AuditAction.RFQ_CREATED,entityType:'RFQ',entityId:rfq.id,after:rfq});return rfq;});}
 mine(){return this.prisma.tenantTransaction(this.tenant.organizationId,tx=>tx.rFQ.findMany({orderBy:{createdAt:'desc'},include:{items:true,quotes:{select:{id:true,status:true,supplierOrgId:true}}}}));}
 async get(id:string){return this.prisma.tenantTransaction(this.tenant.organizationId,async tx=>{const r=await tx.rFQ.findUnique({where:{id},include:{items:{include:{sku:true}},quotes:{include:{items:true}}}});if(!r)throw new NotFoundException('RFQ غير موجود أو غير متاح');return r;});}
 async transition(id:string,to:RFQStatus){return this.prisma.tenantTransaction(this.tenant.organizationId,async tx=>{const r=await tx.rFQ.findUnique({where:{id}});if(!r)throw new NotFoundException('RFQ غير موجود');assertRfqTransition(r.status,to);const u=await tx.rFQ.update({where:{id},data:{status:to}});await this.audit.record(tx,{organizationId:this.tenant.organizationId,userId:this.tenant.userId,action:AuditAction.STATUS_CHANGE,entityType:'RFQ',entityId:id,before:r,after:u});return u;});}
}
