'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, accessToken } from '../../lib/api';

type EntityType='RFQ'|'QUOTE'|'ORDER_INTENT';
export function TransactionWorkspace({entityType,entityId}:{entityType:EntityType;entityId:string}){
 const [conversation,setConversation]=useState<any>(null); const [messages,setMessages]=useState<any[]>([]); const [documents,setDocuments]=useState<any[]>([]); const [body,setBody]=useState(''); const [status,setStatus]=useState('');
 const token=accessToken();
 const refresh=useCallback(async()=>{if(!token)return; try{const c=await api<any>('/conversations',{method:'POST',body:JSON.stringify({entityType,entityId})},token); setConversation(c); const [m,d]=await Promise.all([api<any[]>(`/conversations/${c.id}/messages`,{},token),api<any[]>(`/documents/${entityType}/${entityId}`,{},token)]);setMessages(m);setDocuments(d);}catch(e:any){setStatus(e.message)}},[entityType,entityId,token]);
 useEffect(()=>{refresh()},[refresh]);
 async function send(){if(!token||!conversation||!body.trim())return; try{await api(`/conversations/${conversation.id}/messages`,{method:'POST',body:JSON.stringify({body})},token);setBody('');await refresh()}catch(e:any){setStatus(e.message)}}
 async function registerFile(file:File){if(!token)return; try{setStatus('Preparing document…');const prepared=await api<any>('/documents/prepare',{method:'POST',body:JSON.stringify({entityType,entityId,fileName:file.name,mimeType:file.type||'application/octet-stream',byteSize:file.size,visibilityToCounterparty:true})},token);const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());const sha=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');await api(`/documents/${prepared.documentId}/complete`,{method:'POST',body:JSON.stringify({sha256:sha})},token);setStatus('Document registered. Connect the StorageAdapter before production file transfer.');await refresh()}catch(e:any){setStatus(e.message)}}
 return <section className="mt-10 rounded-3xl border border-white/10 bg-white/[.025] p-5 md:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs tracking-[.25em] text-white/35">TRANSACTION WORKSPACE</div><h2 className="mt-2 text-xl font-semibold">Messages & Documents</h2></div><label className="cursor-pointer rounded-xl border border-white/15 px-4 py-2 text-sm hover:bg-white/[.05]">Add document<input type="file" className="hidden" onChange={e=>e.target.files?.[0]&&registerFile(e.target.files[0])}/></label></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-white/10"><div className="max-h-72 min-h-44 space-y-3 overflow-y-auto p-4">{messages.map(m=><div key={m.id} className="rounded-xl bg-white/[.05] p-3"><div className="text-[10px] uppercase tracking-wider text-white/35">{m.senderOrgId?.slice(0,8)} · {new Date(m.createdAt).toLocaleString()}</div><div className="mt-1 text-sm text-white/85">{m.body}</div></div>)}{!messages.length&&<div className="py-12 text-center text-sm text-white/35">No messages yet. Keep negotiation context attached to the transaction.</div>}</div><div className="flex gap-2 border-t border-white/10 p-3"><input value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write a commercial message…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black px-3 py-2 text-sm outline-none"/><button onClick={send} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black">Send</button></div></div><div className="rounded-2xl border border-white/10 p-4"><div className="text-sm font-medium">Shared documents</div><div className="mt-3 space-y-2">{documents.map(d=><div key={d.id} className="rounded-xl bg-white/[.04] p-3"><div className="truncate text-sm">{d.fileName}</div><div className="mt-1 text-[11px] text-white/35">{d.mimeType} · SHA-256 verified metadata</div></div>)}{!documents.length&&<div className="py-8 text-center text-xs text-white/35">No shared documents</div>}</div></div></div>{status&&<div className="mt-4 text-xs text-white/45">{status}</div>}</section>
}
