import { SeptlionOfferModule } from './septlion-offer/offer.module';
import { RequirementModule } from './requirement/requirement.module';
import { TradeCoreModule } from './trade-core/trade-core.module';
import { FeedRequirementModule } from './feed-requirement/feed-requirement.module';
import { DemandIntelligenceModule } from './demand-intelligence/demand-intelligence.module';
import { Module } from '@nestjs/common'; import { APP_GUARD, APP_INTERCEPTOR } from '@nestjs/core';
import { DocumentsModule } from './documents/documents.module'; import { MessagingModule } from './messaging/messaging.module'; import { NotificationsModule } from './notifications/notifications.module'; import { OutboxModule } from './outbox/outbox.module';
import { MaritimeRfqModule } from './maritime-rfq/maritime-rfq.module';
import { PrismaModule } from './prisma/prisma.module'; import { AuthModule } from './auth/auth.module'; import { SectorsModule } from './sectors/sectors.module'; import { CatalogModule } from './catalog/catalog.module'; import { RfqModule } from './rfq/rfq.module'; import { QuoteModule } from './quote/quote.module'; import { OrderIntentModule } from './order-intent/order-intent.module'; import { AuditModule } from './audit/audit.module'; import { SupplierMatchingModule } from './supplier-matching/supplier-matching.module'; import { RolesGuard } from './common/roles.guard'; import { TenantContextService } from './common/tenant/tenant-context.service'; import { TenantInterceptor } from './common/tenant/tenant.interceptor';
@Module({imports:[PrismaModule,AuditModule,AuthModule,SectorsModule,CatalogModule,RfqModule,MaritimeRfqModule,QuoteModule,OrderIntentModule,SupplierMatchingModule,DocumentsModule,MessagingModule,NotificationsModule,OutboxModule,DemandIntelligenceModule,FeedRequirementModule,TradeCoreModule,RequirementModule,SeptlionOfferModule],providers:[TenantContextService,{provide:APP_GUARD,useClass:RolesGuard},{provide:APP_INTERCEPTOR,useClass:TenantInterceptor}]}) export class AppModule{}
