import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const allowedOrigins=new Set(["https://septlion.com","https://www.septlion.com"]);
const corsFor=(req:Request)=>{const origin=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":allowedOrigins.has(origin)?origin:"https://septlion.com","Vary":"Origin","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"}};
let cors:Record<string,string>={};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const numberFrom=(v:unknown)=>{const m=String(v||"").match(/\d+(?:[.,]\d+)?/);return m?Number(m[0].replace(",",".")):null};
Deno.serve(async(req)=>{
 cors=corsFor(req);
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const url=Deno.env.get("SUPABASE_URL")!,keys=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}"),secret=keys.default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!secret)return out({error:"Server configuration unavailable"},500);
 const admin=createClient(url,secret,{auth:{persistSession:false}}),db=admin.schema("core"),token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");
 if(!token)return out({error:"Authentication required"},401);const {data:{user},error:ae}=await admin.auth.getUser(token);if(ae||!user)return out({error:"Invalid session"},401);
 const now=new Date().toISOString();let {data:profile,error:pe}=await db.from("User").select("id,email,firstName,lastName").eq("id",user.id).maybeSingle();if(pe)return out({error:"Core profile lookup failed"},500);
 if(!profile){const {error:e}=await db.from("User").insert({id:user.id,email:user.email||`${user.id}@user.invalid`,passwordHash:"SUPABASE_AUTH",isActive:true,sessionVersion:1,createdAt:now,updatedAt:now});if(e)return out({error:"Core profile provisioning failed"},500);profile={id:user.id,email:user.email};}
 let {data:membership,error:me}=await db.from("Membership").select("id,organizationId,role").eq("userId",user.id).order("createdAt").limit(1).maybeSingle();if(me)return out({error:"Membership lookup failed"},500);
 if(!membership){const orgId=crypto.randomUUID(),mid=crypto.randomUUID();const {error:oe}=await db.from("Organization").insert({id:orgId,name:user.email?.split("@")[0]||"Buyer",organizationType:"BUYER",status:"ACTIVE",createdAt:now,updatedAt:now});if(oe)return out({error:"Organization provisioning failed"},500);const {error:mie}=await db.from("Membership").insert({id:mid,userId:user.id,organizationId:orgId,role:"BUYER",createdAt:now});if(mie)return out({error:"Membership provisioning failed"},500);membership={id:mid,organizationId:orgId,role:"BUYER"};}
 if((user.email||"").toLowerCase()==="info@septlion.com"){const {data:existingOp}=await db.from("Membership").select("id").eq("userId",user.id).eq("organizationId","septlion-operator").maybeSingle();if(!existingOp)await db.from("Membership").insert({id:crypto.randomUUID(),userId:user.id,organizationId:"septlion-operator",role:"ADMIN",createdAt:now});}
 const {data:operatorMembership}=await db.from("Membership").select("role").eq("userId",user.id).eq("organizationId","septlion-operator").in("role",["SALES","ADMIN"]).limit(1).maybeSingle();
 const body=await req.json().catch(()=>({})),action=String(body.action||"me");
 const mutations=new Set(["requirements.create","offers.issue","offers.accept","transactions.advance","receipt.accept","claims.open","reorder.create","maritime.create","supply.add","outbox.retry"]);const {data:allowed,error:rateError}=await db.rpc("check_edge_rate_limit",{p_user_id:user.id,p_action:action,p_limit:mutations.has(action)?20:120});if(rateError)return out({error:"Rate limit check failed"},500);if(!allowed)return out({error:"Too many requests"},429);
 if(action==="me")return out({user:profile,membership,isOperator:Boolean(operatorMembership)});
 if(action==="requirements.list"){const {data,error}=await db.from("QualifiedRequirement").select("id,product,packing,containerCount,septlionScale,incoterm,deliveryPort,deliveryCountry,paymentPreference,status,createdAt").eq("organizationId",membership.organizationId).order("createdAt",{ascending:false}).limit(100);return error?out({error:error.message},500):out({items:data||[]});}
 if(action==="requirements.get"){const id=String(body.id||"");const {data,error}=await db.from("QualifiedRequirement").select("*").eq("id",id).eq("organizationId",membership.organizationId).maybeSingle();if(error)return out({error:error.message},500);if(!data)return out({error:"Requirement not found"},404);const {data:rfq}=await db.from("RFQ").select("id,reference,status").eq("requirementId",id).maybeSingle();let offer=null,transaction=null;if(rfq){const o=await db.from("SeptlionOffer").select("id,status,currency,validUntil,currentRevision").eq("rfqId",rfq.id).maybeSingle();offer=o.data;if(offer){const l=await db.from("CommercialLock").select("id").eq("offerId",offer.id).maybeSingle();if(l.data){const tx=await db.from("TradeTransaction").select("id,reference,status,updatedAt").eq("commercialLockId",l.data.id).maybeSingle();transaction=tx.data;}}}return out({item:data,rfq,offer,transaction});}
 if(action==="requirements.create"){const i=body.input||{},product=String(i.product||"").trim(),market=String(i.destination||i.market||"").trim();if(!product||!market)return out({error:"Product and destination are required"},400);const q=numberFrom(i.quantity),cc=Math.max(0,Math.trunc(numberFrom(i.containerCount??(String(i.quantity||"").toUpperCase().includes("FCL")?i.quantity:0))||0));const packing=typeof i.packing==="string"?{display:i.packing}:i.packing||null;const payload={...i,product,market,quantityNumber:q,containerCount:cc||null,unit:i.unit||(String(i.quantity||"").toUpperCase().includes("FCL")?"FCL":"UNIT"),packing,knownFacts:i.knownFacts||i};const {data,error}=await db.rpc("create_buyer_requirement",{p_org_id:membership.organizationId,p_user_id:user.id,p_input:payload});if(error)return out({error:error.message},500);const {data:item}=await db.from("QualifiedRequirement").select("id,product,packing,containerCount,septlionScale,incoterm,deliveryPort,deliveryCountry,paymentPreference,status,createdAt").eq("id",data.requirementId).single();return out({item,rfq:{id:data.rfqId,reference:data.reference}},201);}
 if(action==="offers.list"){const {data,error}=await db.from("SeptlionOffer").select("id,requirementId,rfqId,status,currentRevision,currency,validUntil,createdAt,updatedAt").eq("buyerOrgId",membership.organizationId).order("updatedAt",{ascending:false}).limit(100);return error?out({error:error.message},500):out({items:data||[]});}
 if(action==="offers.get"){const id=String(body.id||"");const {data,error}=await db.from("SeptlionOffer").select("*").eq("id",id).eq("buyerOrgId",membership.organizationId).maybeSingle();if(error)return out({error:error.message},500);if(!data)return out({error:"Offer not found"},404);const {data:revision}=await db.from("SeptlionOfferRevision").select("*").eq("offerId",id).eq("revisionNo",data.currentRevision).maybeSingle();return out({item:data,revision});}
 if(action==="operator.dashboard"){if(!operatorMembership)return out({error:"Operator access required"},403);const {data:health,error}=await db.rpc("platform_health_snapshot");if(error)return out({error:error.message},500);const [{data:signals},{data:opps},{data:supply},{data:outbox},{data:approvals}]=await Promise.all([db.from("DemandSignal").select("id,market,product,score,status,publishedAt,sourceUrl").order("lastSeenAt",{ascending:false}).limit(20),db.from("Opportunity").select("id,reference,status,title,market,product,nextAction,nextActionAt,commercialValue,currency").order("updatedAt",{ascending:false}).limit(20),db.from("SupplyCandidate").select("id,opportunityId,supplierName,country,confidence,verified,sourceUrl").order("updatedAt",{ascending:false}).limit(30),db.from("OutboxEvent").select("id,type,aggregateType,aggregateId,status,attempts,lastError,createdAt").order("createdAt",{ascending:false}).limit(30),db.from("HumanApproval").select("id,opportunityId,action,decision,title,summary,createdAt").eq("decision","PENDING").order("createdAt",{ascending:false}).limit(30)]);return out({health,signals:signals||[],opportunities:opps||[],supply:supply||[],outbox:outbox||[],approvals:approvals||[]});}
 if(action==="supply.add"){if(!operatorMembership)return out({error:"Operator access required"},403);const x=body.input||{};if(!x.opportunityId||!x.supplierName)return out({error:"Opportunity and supplier are required"},400);const row={id:crypto.randomUUID(),opportunityId:String(x.opportunityId),supplierOrgId:x.supplierOrgId||null,supplierName:String(x.supplierName),country:x.country||null,source:x.source||"OPERATOR",sourceUrl:x.sourceUrl||null,capability:x.capability||{},compliance:x.compliance||{},commercial:x.commercial||{},logistics:x.logistics||{},confidence:Math.max(0,Math.min(100,Number(x.confidence)||0)),verified:Boolean(x.verified),createdAt:now,updatedAt:now};const {data,error}=await db.from("SupplyCandidate").insert(row).select("*").single();return error?out({error:error.message},400):out(data,201);}
 if(action==="outbox.retry"){if(!operatorMembership)return out({error:"Operator access required"},403);const id=String(body.id||"");const {data,error}=await db.from("OutboxEvent").update({status:"PENDING",attempts:0,lastError:null,availableAt:now}).eq("id",id).eq("status","FAILED").select("*").maybeSingle();return error?out({error:error.message},400):out({item:data});}
 if(action==="analytics.snapshot"){if(!operatorMembership)return out({error:"Operator access required"},403);const {data,error}=await db.rpc("platform_health_snapshot");return error?out({error:error.message},500):out(data);}
 if(action==="operator.queue"){if(!operatorMembership)return out({error:"Operator access required"},403);const [{data:rfqs},{data:transactions}]=await Promise.all([db.from("RFQ").select("id,reference,status,requirementId,buyerOrgId,deliveryCountry,deliveryPort,incoterm,createdAt").eq("supplierOrgId","septlion-operator").in("status",["OPEN","QUOTED","NEGOTIATING"]).order("createdAt",{ascending:false}).limit(100),db.from("TradeTransaction").select("id,reference,status,buyerOrgId,updatedAt").eq("supplierOrgId","septlion-operator").neq("status","COMPLETED").order("updatedAt",{ascending:false}).limit(100)]);return out({rfqs:rfqs||[],transactions:transactions||[]});}
 if(action==="offers.issue"){if(!operatorMembership)return out({error:"Operator access required"},403);const rfqId=String(body.rfqId||"");const snapshot=body.snapshot||{};const {data,error}=await db.rpc("issue_septlion_offer",{p_rfq_id:rfqId,p_user_id:user.id,p_snapshot:snapshot,p_currency:String(body.currency||"USD"),p_valid_until:body.validUntil||null});return error?out({error:error.message},400):out(data,201);}
 if(action==="offers.accept"){const {data,error}=await db.rpc("accept_septlion_offer",{p_offer_id:String(body.offerId||""),p_buyer_org_id:membership.organizationId,p_user_id:user.id});return error?out({error:error.message},400):out(data);}
 if(action==="transactions.list"){const {data,error}=await db.from("TradeTransaction").select("id,reference,status,version,createdAt,updatedAt").eq("buyerOrgId",membership.organizationId).order("updatedAt",{ascending:false}).limit(100);return error?out({error:error.message},500):out({items:data||[]});}
 if(action==="transactions.get"){const id=String(body.id||"");const {data,error}=await db.from("TradeTransaction").select("*").eq("id",id).eq("buyerOrgId",membership.organizationId).maybeSingle();if(error)return out({error:error.message},500);if(!data)return out({error:"Transaction not found"},404);const [{data:milestones},{data:receipt},{data:events},{data:commercialLock}]=await Promise.all([db.from("TradeMilestone").select("*").eq("transactionId",id).eq("buyerVisible",true).order("sequence"),db.from("TradeReceipt").select("*").eq("transactionId",id).maybeSingle(),db.from("TradeEvent").select("*").eq("transactionId",id).in("visibility",["BUYER"]).order("sequence"),db.from("CommercialLock").select("id,lockedAt,snapshotHash,snapshot").eq("id",data.commercialLockId).maybeSingle()]);return out({item:data,commercialLock,milestones:milestones||[],receipt,events:events||[]});}
 if(action==="transactions.advance"){if(!operatorMembership)return out({error:"Operator access required"},403);const {data,error}=await db.rpc("advance_trade_transaction",{p_transaction_id:String(body.transactionId||""),p_status:String(body.status||""),p_milestone_code:String(body.milestoneCode||""),p_user_id:user.id});return error?out({error:error.message},400):out(data);}
 if(action==="receipt.accept"){const {data,error}=await db.rpc("accept_trade_receipt",{p_transaction_id:String(body.transactionId||""),p_buyer_org_id:membership.organizationId,p_user_id:user.id});if(error)return out({error:error.message},400);await db.rpc("complete_trade_memory",{p_transaction_id:String(body.transactionId||"")});return out(data);}
 if(action==="claims.open"){const {data,error}=await db.rpc("open_trade_claim",{p_transaction_id:String(body.transactionId||""),p_buyer_org_id:membership.organizationId,p_user_id:user.id,p_description:String(body.description||"")});return error?out({error:error.message},400):out(data,201);}
 if(action==="reorder.create"){const q=body.quantity==null?null:Number(body.quantity);const {data,error}=await db.rpc("reorder_trade_transaction",{p_transaction_id:String(body.transactionId||""),p_buyer_org_id:membership.organizationId,p_user_id:user.id,p_quantity:Number.isFinite(q)?q:null});return error?out({error:error.message},400):out(data,201);}
 if(action==="maritime.create"){const i=body.input||{},count=Math.max(1,Math.trunc(Number(i.containerCount)||1)),type=String(i.containerType||"20FT"),pol=String(i.pol||""),pod=String(i.pod||""),shipDate=String(i.shipDate||"");if(!pol||!pod||!shipDate)return out({error:"Route and ship date are required"},400);const level=count<=7?"S-1":count<=19?"S-2":count<=49?"S-3":count<=99?"S-4":count<=299?"S-5":count<=999?"S-6":"S-7",term=level==="S-1"?"Spot FCL":level==="S-2"?"Scheduled FCL":level==="S-3"?"Space Allocation":level==="S-4"?"Block Space":level==="S-5"?"Coastal Charter":level==="S-6"?"Feeder Charter":"Full Charter & Bulk",bases:any={"20FT":1650,"40FT":2600,"REEFER":4300,"OPEN_TOP":3350,"FLAT_RACK":3900,"BULK":5200},base=bases[type]||2200,longHaul=/China|Rotterdam|Türkiye/.test(pol+pod)?1.42:1,volume=Math.max(.78,1-Math.min(count,300)*.0007),freight=base*longHaul*volume,factor=1.16,min=Math.round(freight*.9*factor/50)*50,max=Math.round(freight*1.18*factor/50)*50,id=crypto.randomUUID(),reference=`MRFQ-${new Date().getUTCFullYear()}-${id.slice(0,8).toUpperCase()}`,valid=new Date(Date.now()+7*86400000).toISOString();const row={id,reference,idempotencyKey:String(i.idempotencyKey||id),customerName:String(i.customerName||user.email||"Buyer"),company:String(i.company||"Buyer"),email:String(i.email||user.email||""),phone:String(i.phone||""),containerCount:count,containerType:type,teu:type==="40FT"?count*2:count,pol,pod,incoterm:String(i.incoterm||"FOB"),cargoType:String(i.cargoType||"GENERAL"),shipDate:new Date(shipDate).toISOString(),grossWeight:i.grossWeight||null,cbm:i.cbm||null,finalDestinations:Math.max(1,Number(i.finalDestinations)||1),paymentTerm:i.paymentTerm||null,notes:i.notes||null,sCode:level,exclusiveName:level,maritimeTerm:term,priceMin:min,priceMax:max,currency:"USD",surcharges:[{code:"BAF",rate:8},{code:"CAF",rate:3},{code:"PSS",rate:5}],validUntil:valid,status:"ESTIMATED",createdAt:now,updatedAt:now};const {data,error}=await db.from("MaritimeRFQ").insert(row).select("id,reference,priceMin,priceMax,validUntil,sCode,status").single();return error?out({error:error.message},400):out(data,201);}
 if(action==="documents.list"){const entityId=String(body.entityId||"");const entityType=String(body.entityType||"TRANSACTION");if(!entityId)return out({error:"Entity required"},400);if(entityType==="TRANSACTION"){const {data:tx}=await db.from("TradeTransaction").select("id").eq("id",entityId).eq("buyerOrgId",membership.organizationId).maybeSingle();if(!tx)return out({error:"Transaction not found"},404);}const {data,error}=await db.from("CommercialDocument").select("id,fileName,mimeType,byteSize,status,createdAt,entityType,entityId").eq("organizationId",membership.organizationId).eq("entityType",entityType).eq("entityId",entityId).eq("status","READY").order("createdAt",{ascending:false});return error?out({error:error.message},500):out({items:data||[]});}
 if(action==="notifications.list"){const {data,error}=await db.from("Notification").select("*").eq("organizationId",membership.organizationId).or(`userId.is.null,userId.eq.${user.id}`).order("createdAt",{ascending:false}).limit(50);return error?out({error:error.message},500):out({items:data||[]});}
 return out({error:"Unsupported action"},400);
});